[versions]
agp = "9.0.0"
kotlin = "2.3.0"
coreKtx = "1.17.0"
google-services = "4.4.4"
devtools-ksp = "2.3.2"
kotlin-serialization = "2.3.0"
kotlin-parcelize = "2.3.20-Beta1"

# dependiences
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
kotlinxCoroutinesAndroid = "1.10.2"
kotlinxCoroutinesCore = "1.10.2"
kotlinStdlib = "2.3.0"
activityCompose = "1.12.3"
composeBom = "2026.01.01"
kotlinxDatetime = "0.7.1"
workRuntime = "2.11.1"

# General Library
material = "1.13.0"
constraintlayout = "2.2.1"
navigationFragmentKtx = "2.9.7"
navigationUiKtx = "2.9.7"
coordinatorlayout = "1.3.0"
lifecycleLivedataKtx = "2.10.0"
lifecycleViewmodelKtx = "2.10.0"
drawerlayout = "1.2.0"
gridlayout = "1.1.0"
palette = "1.0.0"
preference = "1.2.1"
recyclerview = "1.4.0"
swiperefreshlayout = "1.2.0"
vectordrawableAnimated = "1.2.0"
cardview = "1.0.0"
viewpager2 = "1.1.0"
fragmentKtx = "1.8.9"
foundation = "1.10.2"
material3 = "1.4.0"
material3AdaptiveNavigationSuite = "1.5.0-alpha13"
material3WindowSizeClass = "1.4.0"
datastorePreferences = "1.2.0"
coreSplashscreen = "1.2.0"

# Messaging, Database & Ads
playServicesAds = "24.9.0"
androidxCredentials = "1.5.0"
googleId = "1.2.0"
inappSdk = "5.3.0"
unityAds = "4.16.6"
billing = "8.3.0"
okhttp = "5.3.2"
glide = "5.0.5"
gson = "2.13.2"
retrofit = "3.0.0"

# Websocket & other
centrifugeJava = "0.5.0"
ytDlpLibrary = "0.18.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinStdlib" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
work-gcm = { module = "androidx.work:work-gcm", version.ref = "workRuntime" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntime" }
work-rxjava2 = { module = "androidx.work:work-rxjava2", version.ref = "workRuntime" }
work-testing = { module = "androidx.work:work-testing", version.ref = "workRuntime" }

# General Library
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleLivedataKtx" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "coordinatorlayout" }
drawerlayout = { module = "androidx.drawerlayout:drawerlayout", version.ref = "drawerlayout" }
gridlayout = { module = "androidx.gridlayout:gridlayout", version.ref = "gridlayout" }
palette = { module = "androidx.palette:palette", version.ref = "palette" }
preference = { module = "androidx.preference:preference", version.ref = "preference" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
vectordrawable-animated = { module = "androidx.vectordrawable:vectordrawable-animated", version.ref = "vectordrawableAnimated" }
viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
androidx-fragment-compose = { module = "androidx.fragment:fragment-compose", version.ref = "fragmentKtx" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-fragment-testing = { module = "androidx.fragment:fragment-testing", version.ref = "fragmentKtx" }
androidx-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "foundation" }
androidx-material3-adaptive-navigation-suite = { module = "androidx.compose.material3:material3-adaptive-navigation-suite", version.ref = "material3AdaptiveNavigationSuite" }
androidx-material3-window-size-class1 = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3WindowSizeClass" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }

# Messaging, Database & Ads
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "androidxCredentials" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "androidxCredentials" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleId" }
unity-ads = { module = "com.unity3d.ads:unity-ads", version.ref = "unityAds" }
inapp-sdk = { module = "com.startapp:inapp-sdk", version.ref = "inappSdk" }
billing = { module = "com.android.billingclient:billing", version.ref = "billing" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }

# Websocket & other
centrifuge-java = { module = "io.github.centrifugal:centrifuge-java", version.ref = "centrifugeJava" }
# https://github.com/yausername/youtubedl-android
yt-dlp-library = { module = "io.github.junkfood02.youtubedl-android:library", version.ref = "ytDlpLibrary" }
yt-dlp-ffmpeg = { module = "io.github.junkfood02.youtubedl-android:ffmpeg", version.ref = "ytDlpLibrary" }
yt-dlp-aria2c = { module = "io.github.junkfood02.youtubedl-android:aria2c", version.ref = "ytDlpLibrary" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-services = {id = 'com.google.gms.google-services', version.ref = 'google-services'}
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "devtools-ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-serialization" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin-parcelize" }
